language: c
script: ./.travis-ci.sh
matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.03
    - os: linux
      env: OCAML_VERSION=4.04
    - os: linux
      env: OCAML_VERSION=4.05
    # in addition, test opam package build (PACKAGE="piqilib")
    - os: linux
      env: OCAML_VERSION=4.06 PACKAGE="piqilib"
        # in addition, test opam package build (PACKAGE="piqilib")
    - os: linux
      env: OCAML_VERSION=4.07 PACKAGE="piqilib"
        # in addition, test opam package build (PACKAGE="piqilib")
    - os: linux
      env: OCAML_VERSION=4.08 PACKAGE="piqilib"
    # testing only basic install on osx with latest homebrew formulas
    - os: osx
      env: OCAML_VERSION=homebrew
      before_script:
        - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        - rvm get head  # workaround for https://github.com/travis-ci/travis-ci/issues/6307
branches:
  only:
    - master
